version: '3.4'
services:
  backend:
    container_name: backend
    build:
      context: backend/
    #command: bash -c "python app.py"
    volumes:
      - ./backend/:/app
    ports:
      - 8000:8000
    restart:
      on-failure
    networks:
      - front_back

  frontend:
    build:
      context: Frontend/
    ports:
      - 80:80
    depends_on:
      - backend
    restart:
      on-failure
    networks:
      - front_back


  redis:
    container_name: redis
    image: "redis:alpine"
    networks:
      - front_back

  celery:
    build:
      context: backend/
    command: celery -A app.celery worker -l info
    volumes:
      - ./gitdiff/:/usr/src/app/
      - ./gitdiff/tmp/:/app/tmp/
    depends_on:
      - redis
    networks:
      - front_back
    links:
      - redis

networks:
  front_back: